import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ManualHandoff,HandoffStore,HANDOFF_ID,handoffContext} from '../src/manual-handoff.mjs';
function fixture(t,{failProvider=false,busy=false,failPrompt=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'handoff-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const store=new HandoffStore(dir),sent=[],calls=[],agents=[];
 const makeAgent=(emit)=>{const n=agents.length+1;const a={emit,ready:Promise.resolve({}),closed:false,reply:()=>false,write:m=>calls.push(m),close(){this.closed=true},async call(method,params){calls.push({method,params});
 if(method==='session/new')return {sessionId:'branch-'+n};
 if(method==='session/set_config_option'){if(failProvider&&params.configId==='provider')throw new Error('PROVIDER_AUTH_FAILED');return {configOptions:[{id:'provider',currentValue:params.value},{id:'model',category:'model',currentValue:'m1',options:[{value:'m1',name:'m1'}]}]};}
 if(method==='session/load'){emit({method:'session/update',params:{sessionId:params.sessionId,update:{sessionUpdate:'user_message_chunk',content:{type:'text',text:'private context packet'}}}});return {sessionId:params.sessionId,configOptions:[]};}
 if(method==='session/prompt'){if(failPrompt)throw new Error('RATE_LIMIT');emit({method:'session/update',params:{sessionId:params.sessionId,update:{sessionUpdate:'agent_message_chunk',content:{type:'text',text:'answer'}}}});return {stopReason:'end_turn'};}
 return {};}};agents.push(a);return a;};
 const c=new ManualHandoff({store,send:m=>sent.push(m),makeAgent,isBusy:()=>busy});t.after(()=>c.close());
 const load=(sid,text)=>{c.track({id:'load-'+sid,method:'session/load',params:{sessionId:sid,cwd:'/project/'+sid}});c.outgoing({method:'session/update',params:{sessionId:sid,update:{sessionUpdate:'user_message_chunk',content:{type:'text',text}}}});return c.outgoing({id:'load-'+sid,result:{configOptions:[]}});};
 const select=(sid,value='minimax')=>c.handle({id:'select',method:'session/set_config_option',params:{sessionId:sid,configId:HANDOFF_ID,value}});
 return {store,sent,calls,agents,c,load,select,dir,makeAgent};
}
test('successful source load exposes manual selector; failed load cannot switch',async t=>{const f=fixture(t);assert.equal(f.load('a','A').result.configOptions[0].id,HANDOFF_ID);await f.select('missing');assert.match(f.sent.at(-1).error.message,/完整載入/);assert.equal(f.agents.length,0);});
test('selected source alone is transferred, mode approve is set before committing',async t=>{const f=fixture(t);f.load('a','ONLY_A');f.load('b','SECRET_B');await f.select('a');assert.equal(f.store.records.get('a').provider,'minimax');assert.ok(f.calls.some(x=>x.method==='session/set_mode'&&x.params.modeId==='approve'));assert.equal(f.calls.some(x=>x.method==='session/prompt'),false);await f.c.handle({id:3,method:'session/prompt',params:{sessionId:'a',prompt:[{type:'text',text:'continue'}]}});const prompt=f.calls.find(x=>x.method==='session/prompt').params.prompt;assert.match(prompt[0].text,/ONLY_A/);assert.doesNotMatch(prompt[0].text,/SECRET_B/);assert.equal(f.sent.find(x=>x.method==='session/update').params.sessionId,'a');assert.equal(f.store.records.get('a').contextPending,undefined);});
test('provider failure retains original without routing or history mutation',async t=>{const f=fixture(t,{failProvider:true});f.load('a','A');await f.select('a');assert.equal(f.store.records.size,0);assert.match(f.sent.at(-1).error.message,/PROVIDER_AUTH_FAILED/);assert.equal(f.c.observed.get('a').messages[0].text,'A');assert.ok(f.agents[0].closed);});
test('busy conversation rejects switching before any agent is created',async t=>{const f=fixture(t,{busy:true});f.load('a','A');await f.select('a');assert.equal(f.agents.length,0);assert.match(f.sent.at(-1).error.message,/仍在執行/);});
test('unknown target cannot be used',async t=>{const f=fixture(t);f.load('a','A');await f.select('a','unapproved');assert.equal(f.agents.length,0);assert.match(f.sent.at(-1).error.message,/不支援/);});
test('long history fails without silent truncation',()=>{assert.throws(()=>handoffContext([{role:'user',text:'a'.repeat(200001)}]),/上限/);});
test('reconnect loads branch and replays display history without leaking packet',async t=>{const f=fixture(t);f.load('a','ORIGINAL');await f.select('a');const reopened=new HandoffStore(f.dir);assert.ok(reopened.hidden('branch-1'));const sent=[];const c=new ManualHandoff({store:reopened,send:m=>sent.push(m),makeAgent:f.makeAgent});t.after(()=>c.close());await c.handle({id:1,method:'session/load',params:{sessionId:'a'}});assert.equal(sent[0].params.update.content.text,'ORIGINAL');assert.equal(sent.at(-1).result.sessionId,'a');assert.doesNotMatch(JSON.stringify(sent),/private context packet/);});
test('prompt failure prevents blind retry and keeps pending context',async t=>{const f=fixture(t,{failPrompt:true});f.load('a','A');await f.select('a');const msg={id:2,method:'session/prompt',params:{sessionId:'a',prompt:[{type:'text',text:'next'}]}};await f.c.handle(msg);assert.match(f.sent.at(-1).error.message,/RATE_LIMIT/);assert.ok(f.store.records.get('a').contextPending);await f.c.handle(msg);assert.match(f.sent.at(-1).error.message,/未確認完成/);assert.equal(f.calls.filter(x=>x.method==='session/prompt').length,1);});
test('second selection creates separate branch, keeps complete text and hides old branch',async t=>{const f=fixture(t);f.load('a','A');await f.select('a');await f.c.handle({id:2,method:'session/prompt',params:{sessionId:'a',prompt:[{type:'text',text:'next'}]}});await f.select('a','codex-acp');const r=f.store.records.get('a');assert.equal(r.provider,'codex-acp');assert.match(r.contextPending,/answer/);assert.ok(f.store.hidden('branch-1'));assert.ok(f.store.hidden('branch-2'));assert.ok(f.agents[0].closed);});
test('direct provider mutation is rejected so context cannot be bypassed',async t=>{const f=fixture(t);f.load('a','A');await f.select('a');await f.c.handle({id:3,method:'session/set_config_option',params:{sessionId:'a',configId:'provider',value:'other'}});assert.match(f.sent.at(-1).error.message,/接棒模型/);});

test('Goose model dialog same-provider step retains original Claude ACP session',async t=>{const f=fixture(t);const sid='external-claude:fixture';f.load(sid,'A');await f.c.handle({id:1,method:'session/set_config_option',params:{sessionId:sid,configId:'provider',value:'claude-acp'}});assert.equal(f.agents.length,0);assert.equal(f.store.records.size,0);assert.equal(f.sent.at(-1).result.configOptions.find(x=>x.id==='provider').currentValue,'claude-acp');});
test('Goose model dialog cross-provider step hands off and same-provider retry is idempotent',async t=>{const f=fixture(t);const sid='external-claude:fixture';f.load(sid,'A');const m={id:1,method:'session/set_config_option',params:{sessionId:sid,configId:'provider',value:'codex-acp'}};await f.c.handle(m);assert.equal(f.store.records.get(sid).provider,'codex-acp');assert.equal(f.sent.at(-1).result.configOptions.find(x=>x.id==='provider').currentValue,'codex-acp');await f.c.handle(m);assert.equal(f.agents.length,1);assert.equal(f.calls.some(x=>x.method==='session/prompt'),false);});
test('long conversation hands off bounded labeled excerpt with complete local archive',async t=>{const f=fixture(t);const original='FIRST_DECISION\n'+'a'.repeat(250000)+'\nLATEST_REQUEST';f.load('a',original);await f.select('a');const r=f.store.records.get('a');assert.ok(r);assert.ok(r.contextPending.length<200000);assert.match(r.contextPending,/不是完整摘要/);assert.match(r.contextPending,/FIRST_DECISION/);assert.match(r.contextPending,/LATEST_REQUEST/);const {readFileSync,statSync}=await import('node:fs');assert.ok(readFileSync(r.historyPath,'utf8').includes(original));assert.equal(statSync(r.historyPath).mode&0o777,0o600);assert.equal(f.calls.some(x=>x.method==='session/prompt'),false);});

test('release original connection only after successful handoff',async t=>{const f=fixture(t),released=[];f.c.releaseSource=sid=>{assert.ok(f.store.records.has(sid));released.push(sid)};f.load('a','A');await f.select('a');assert.deepEqual(released,['a']);});
test('failed handoff retains original connection',async t=>{const f=fixture(t,{failProvider:true}),released=[];f.c.releaseSource=sid=>released.push(sid);f.load('a','A');await f.select('a');assert.deepEqual(released,[]);});

test('branch auto-title preserves source title and unrelated session metadata',async t=>{const f=fixture(t);f.c.titleFor=()=> 'Original title';f.load('a','A');await f.select('a');f.agents[0].emit({method:'session/update',params:{sessionId:'branch-1',update:{sessionUpdate:'session_info_update',title:'Context packet used as title',updatedAt:'2026-09-27'}}});const m=f.sent.at(-1);assert.equal(m.params.sessionId,'a');assert.equal(m.params.update.title,'Original title');assert.equal(m.params.update.updatedAt,'2026-09-27');assert.equal(f.store.records.get('a').sourceTitle,'Original title');});
test('unknown source title never forwards branch title',async t=>{const f=fixture(t);f.load('a','A');await f.select('a');f.agents[0].emit({method:'session/update',params:{sessionId:'branch-1',update:{sessionUpdate:'session_info_update',title:'Context packet'}}});assert.equal(Object.hasOwn(f.sent.at(-1).params.update,'title'),false);});
